#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version = "2"

[linters]
default = "none"
enable = ["asasalint", "asciicheck", "bidichk", "bodyclose", "canonicalheader", "containedctx", "copyloopvar", "cyclop", "decorder", "depguard", "dogsled", "dupl", "dupword", "durationcheck", "embeddedstructfieldcheck", "err113", "errcheck", "errchkjson", "errname", "errorlint", "exhaustive", "exptostd", "fatcontext", "forbidigo", "forcetypeassert", "funcorder", "funlen", "gocheckcompilerdirectives", "gochecknoglobals", "gochecknoinits", "gochecksumtype", "gocognit", "goconst", "gocritic", "gocyclo", "godoclint", "godot", "godox", "goheader", "gomoddirectives", "gomodguard_v2", "goprintffuncname", "gosec", "gosmopolitan", "govet", "grouper", "iface", "importas", "inamedparam", "ineffassign", "interfacebloat", "intrange", "iotamixing", "ireturn", "lll", "loggercheck", "maintidx", "makezero", "mirror", "misspell", "modernize", "musttag", "nakedret", "nestif", "nilerr", "nilnesserr", "nilnil", "nlreturn", "noctx", "noinlineerr", "nolintlint", "nonamedreturns", "paralleltest", "perfsprint", "prealloc", "predeclared", "promlinter", "protogetter", "reassign", "recvcheck", "rowserrcheck", "sloglint", "spancheck", "sqlclosecheck", "staticcheck", "tagalign", "tagliatelle", "testableexamples", "testifylint", "testpackage", "thelper", "tparallel", "unconvert", "unparam", "unqueryvet", "unused", "usestdlibvars", "usetesting", "varnamelen", "wastedassign", "whitespace", "wrapcheck", "wsl_v5"]

[linters.settings.depguard.rules.prevent_unmaintained_packages]
list-mode = "lax"
files = ["$all"]
allow = ["github.com/gofiber/fiber/v2"]
deny = [{ pkg = "io/ioutil", desc = "deprecrated by os&io" }]

[formatters]
enable = ["golines", "gofumpt"]

[formatters.settings.gofumpt]
module-path = "gutils"

[formatters.settings.golines]
max-len = 120
tab-len = 2
shorten-comments = true
reformat-tags = true
chain-split-dots = true

[run]
allow-parallel-runners = true
allow-serial-runners = true
build-tags = []
concurrency = 8
enable-build-vcs = false
go = ""
issues-exit-code = 10
modules-download-mode = "mod"
relative-path-mode = "gomod"
tests = false
timeout = "0"
